// Code generated by "stringer -type nodeType"; DO NOT EDIT.
// (Hand-maintained: regenerate with `go generate` if stringer is installed.)

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant
	// values have changed. Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[assign-0]
	_ = x[operate-1]
	_ = x[variable-2]
	_ = x[constant-3]
	_ = x[rootNode-4]
	_ = x[stringNode-5]
	_ = x[unevalNode-6]
	_ = x[callNode-7]
	_ = x[indexNode-8]
	_ = x[exprseqNode-9]
	_ = x[listNode-10]
	_ = x[setNode-11]
	_ = x[procNode-12]
	_ = x[paramNode-13]
	_ = x[localsNode-14]
	_ = x[globalsNode-15]
	_ = x[optionNode-16]
	_ = x[descriptionNode-17]
	_ = x[ifNode-18]
	_ = x[forNode-19]
	_ = x[returnNode-20]
	_ = x[errorNode-21]
	_ = x[tryNode-22]
	_ = x[useNode-23]
	_ = x[moduleNode-24]
	_ = x[rangeNode-25]
	_ = x[arrowNode-26]
	_ = x[typeNode-27]
	_ = x[memberNode-28]
	_ = x[unaryNode-29]
	_ = x[matrixNode-30]
	_ = x[breakNode-31]
	_ = x[nextNode-32]
	_ = x[readNode-33]
	_ = x[emptyNode-34]
}

var _nodeType_names = []string{
	"assign", "operate", "variable", "constant", "rootNode",
	"stringNode", "unevalNode", "callNode", "indexNode", "exprseqNode",
	"listNode", "setNode", "procNode", "paramNode", "localsNode",
	"globalsNode", "optionNode", "descriptionNode", "ifNode", "forNode",
	"returnNode", "errorNode", "tryNode", "useNode", "moduleNode",
	"rangeNode", "arrowNode", "typeNode", "memberNode", "unaryNode",
	"matrixNode", "breakNode", "nextNode", "readNode", "emptyNode",
}

func (i nodeType) String() string {
	if i < 0 || int(i) >= len(_nodeType_names) {
		return "nodeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _nodeType_names[i]
}
