// Code generated by "stringer -type tokenType"; DO NOT EDIT.
// (Hand-maintained: regenerate with `go generate` if stringer is installed.)

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant
	// values have changed. Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[operator-0]
	_ = x[statementDelim-1]
	_ = x[name-2]
	_ = x[number-3]
	_ = x[assignment-4]
	_ = x[nullToken-5]
	_ = x[stringTok-6]
	_ = x[unevalTok-7]
	_ = x[lparen-8]
	_ = x[rparen-9]
	_ = x[lbracket-10]
	_ = x[rbracket-11]
	_ = x[lbrace-12]
	_ = x[rbrace-13]
	_ = x[langle-14]
	_ = x[rangle-15]
	_ = x[comma-16]
	_ = x[keyword-17]
	_ = x[eofTok-18]
}

var _tokenType_names = []string{
	"operator", "statementDelim", "name", "number", "assignment",
	"nullToken", "stringTok", "unevalTok", "lparen", "rparen",
	"lbracket", "rbracket", "lbrace", "rbrace", "langle",
	"rangle", "comma", "keyword", "eofTok",
}

func (i tokenType) String() string {
	if i < 0 || int(i) >= len(_tokenType_names) {
		return "tokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _tokenType_names[i]
}
